### ISSUE TITLE
Probleme beim der Installation

### ISSUE THREAD

**Issue by 19-Oskar** [croedel/MTECmqtt#4]
Habe folgendes Problem und komme einfach nicht mehr weiter. 
Beim installieren im Termninalprogram von Home Assistant kommt immer der folgende Fehler: 
"Traceback (most recent call last):
  File "/root/mtecmqtt/bin/mtec_mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/mtecmqtt/lib/python3.12/site-packages/mtecmqtt/mtec_mqtt.py", line 114, in main
[INFO] Connected to MQTT broker
    api.connect(ip_addr=cfg['MODBUS_IP'], port=cfg['MODBUS_PORT'], slave=cfg['MODBUS_SLAVE'])
  File "/root/mtecmqtt/lib/python3.12/site-packages/mtecmqtt/MTECmodbusAPI.py", line 32, in connect
    self.modbus_client = ModbusTcpClient(ip_addr, port, framer=Framer(framer), timeout=cfg["MODBUS_TIMEOUT"],
                                                               ^^^^^^^^^^^^^^
TypeError: Framer.__init__() missing 3 required positional arguments: 'params', 'is_server', and 'device_ids'"

Ich bin strikt nach Vorgabe vorgegenagen, was vor einer Woche noch funktioniert hat läuft einfach nicht mehr. Können Sie mir helfen?

**Comment by croedel** [comment]
PyModbus hat eine neue Version releases: V 3.7. Mit der scheinen sich ein paar Dinge geändert zu haben, sodass mein code nicht mehr funktioniert hat.
Ich habe gerade eine neue Version von MTECmqtt erstellt (2.0.3). Damit sollte das Problem behoben sein.

**Comment by 19-Oskar** [comment]
Vielen Dank. Die Installation läuft jetzt wieder, man kann nur das Programm nach dem Aufruf mit CTRL-C nicht mehr stoppen um die generierte config.yaml zu bearbeiten. Komme ab hier wieder nicht weiter.
Vorab vielen Dank für die Hilfe.

**Comment by 19-Oskar** [comment]
Hier noch weitere Fehlermeldungen:
[ERROR] Error while reading register 25100, length 1 from pymodbus
[ERROR] Connection to (192.168.XXX.XXX, 5743) failed: [Errno 111] Connection refused
[ERROR] Exception while reading register 25103, length 1 from pymodbus: Modbus Error: [Connection] Failed to connect[ModbusTcpClient 192.168.XXX.XXX:5743]
[ERROR] Connection to (192.168.XXX.XXX, 5743) failed: [Errno 111] Connection refused
[ERROR] Exception while reading register 52502, length 4 from pymodbus: Modbus Error: [Connection] Failed to connect[ModbusTcpClient 192.168.XXX.XXX:5743]
[WARNING] Retrieved Modbus data is incomplete: '25100'
[WARNING] Cant retrieve initial config - retry in 10 s
